name: Upload scripts to Bunny CDN

on:
  push:
    branches: ['main']
    paths:
      - public/scripts/**

jobs:
  upload-to-cdn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload scripts to Bunny CDN
        run: |
          for file in $(find public/scripts -type f); do
            curl -T "$file" \
              -H "AccessKey: ${{ secrets.BUNNY_STORAGE_API_KEY }}" \
              "https://storage.bunnycdn.com/${{ secrets.BUNNY_STORAGE_ZONE_NAME }}/scripts/$(basename $file)"
          done
