name: Deploy Frontera App

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.2.3)'
        required: true
        type: string
      deploy_middleware:
        description: 'Deploy middleware component'
        required: false
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Download workflow data
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: workflow-data
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read workflow data
        id: workflow_data
        if: github.event_name == 'workflow_run'
        run: |
          next_version=$(cat workflow-data.json | jq -r .next_version)
          echo "next_version=${next_version}" >> $GITHUB_OUTPUT

      - name: Set version
        id: set_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.workflow_data.outputs.next_version }}" >> $GITHUB_OUTPUT
          fi

      - name: Set deploy_middleware flag
        id: set_deploy_middleware
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "deploy_middleware=${{ inputs.deploy_middleware }}" >> $GITHUB_OUTPUT
          else
            echo "deploy_middleware=true" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Frontera App Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FE_TESTS_GITHUB_TOKEN }}
          repository: customeros/cloud
          event-type: deploy-frontera-app
          client-payload: '{"version": "${{ steps.set_version.outputs.version }}"}'

      - name: Trigger Middleware Deployment
        if: steps.set_deploy_middleware.outputs.deploy_middleware == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FE_TESTS_GITHUB_TOKEN }}
          repository: customeros/cloud
          event-type: deploy-frontera-middleware
          client-payload: '{"version": "${{ steps.set_version.outputs.version }}"}'